# Site settings
title: FPGA System-on-Chip Design & Verification Demonstration
author:
  name: Liam Noone
  email: G00420041@atu.ie
description: "FPGA Metallica VGA Project."

# Build settings
remote_theme: jekyll/minima
